# Generated by Django 4.2.5 on 2023-09-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Animal')),
                ('nro_caravana', models.IntegerField(verbose_name='Número de caravana')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo.animales')),
            ],
        ),
        migrations.CreateModel(
            name='Paricion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo.animales')),
            ],
        ),
    ]
