# Generated by Django 4.2.5 on 2023-09-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='cant_pariciones',
            field=models.IntegerField(blank=True, verbose_name='Cant paricion'),
        ),
    ]
