# Generated by Django 4.2.5 on 2023-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0003_alter_animales_cant_pariciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunacion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
