# Generated by Django 4.2.6 on 2023-10-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0005_animales_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muerto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_caravana', models.IntegerField(verbose_name='Número de caravana')),
                ('name', models.CharField(max_length=100, verbose_name='Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Vendido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_caravana', models.IntegerField(verbose_name='Número de caravana')),
                ('name', models.CharField(max_length=100, verbose_name='Animal')),
            ],
        ),
    ]
